[project]
name = "baynext-ml-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Léo Grosjean", email = "leo.grosjean@live.fr" }
]
requires-python = ">=3.12"
dependencies = [
    "typer>=0.16.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/baynext"]
